### ISSUE TITLE
Layered static maps

### ISSUE THREAD

**Issue by tabrasel** [MazamaScience/WRFmet#1]
Ability to create ggplot static images by layering in any order:
- [x] Raster (from WRF or BlueSky or elsewhere)
- [x] Vector field (from U, V rasterBrick)
- [x] Spatial points
- [x] Spatial polygons

Maybe something like this? :
```
createMap(stamenMap) %>%
  layer_raster(elevationRaster) %>%
  layer_polys(statePolys) %>%
  layer_vectorfield(windRaster) %>%
  layer_points(monitorPoints)
```

**Comment by jonathancallahan** [comment]
Just started looking at your work-in-progress and you are absolutely on track with what I think we should provide for this first stage of the **WRFmet** package. We can describe the initial functionality as:

1. Ability to ingest single-tilmestep local WRF output as 'raster' objects
2. Ability to create simple plots of WRF fields.
3. Ability to create **ggplot** static images by layering in any order: raster (from WRF or BlueSky or elsewhere); vector field (from U, V rasterBrick); spatial polygons; spatial points
4. Example "articles" demonstrating how to do this with WRF output, BlueSky runs; **MazamaSpatialUtils** datasets; **PWFSLSmoke** monitor data
