### ISSUE TITLE
Generalize model runs

### ISSUE THREAD

**Issue by tabrasel** [MazamaScience/WRFmet#14]
So far we only have access to [http://m2.airfire.org/PNW/](http://m2.airfire.org/PNW/) for our WRF files. Within the `PNW/` dir are separate directories for `1.33km/` and `4km/`. This is different from how model domains are organized for BlueSky data, which separates PNW into `PNW-1.33km/` and `PNW-4km/`.

Right now, for simplicity's sake in early development, the `baseUrl` for downloading model run files from AirFire is [http://m2.airfire.org/PNW/4km/WRF/](http://m2.airfire.org/PNW/4km/WRF/). In the future though, this will have to be generalized to something like [http://m2.airfire.org/????](http://m2.airfire.org/????) to include other domains like CONUS.

**Comment by jonathancallahan** [comment]
We need to contact Robert Solomon at AirFire to inquire about other model run output.
