### ISSUE TITLE
making plotting WRF-specific

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/WRFmet#19]
This isn't a precisely defined task but I feel the various `plot_~()` and `layer_~()` functions (or some new ones) need some changes to make them more user friendly in the context of working with WRF output.

Here are some specific suggestions for the `layer_~()` functions:

- [x] `layer_vectorField()` accepts separate `uRaster` and `vRaster` _rasterLayers_ as arguments and assumes they are on the same grid. Instead, I think it should accept a `raster` argument (which will be a _RasterBrick_ object) and `uName` and `vName` arguments and create the internal `uvRasterBrick` from that information.
- [x] To work in a similar manner, `layer_raster() should also accept a `raster` and `varName` arguments. As a nicety, it could also handle `raster` being a single variable _rasterLayer_ object in which case `varName` would not be needed (default of `NULL` could be ignored).

And I'm not thrilled about a new "class" of objects implied by the `plot_~()` functions. Instead, I think these should be functions/methods associated with the somewhat abstract `wrf_` objects -- basically just a _RasterBrick_ full of WRF output variables.

Some suggestions for the `plot_~()` functions (now renamed as `wrf_~()` functions:

- [x] `wrf_basePlot()` -- No change except maybe have title default to "WRF output for hour <modelForecastHour> on <modelForecast>". Can we use `raster@title` to help create this?
- [x] `wrf_rasterPlot()` -- Like the functions above, this should accept `raster` and `varName` arguments.
- [x] `wrf_standardPlot()` -- Like the functions above,  this should accept `raster` argument and the names of other parameters for background, U and V.

**Comment by tabrasel** [comment]
`wrf_basePlot()` is always called by higher-level functions like `wrf_rasterPlot()` or `wrf_standardPlot()`, which are actually given the rasters from which we can extract their titles. So I think it is better to set the title of the plot within the higher-level function and just passing that string down to `wrf_basePlot()`.
