### ISSUE TITLE
Reconcile wrf_load() and wrf_loadTimeSeries()

### ISSUE THREAD

**Issue by tabrasel** [MazamaScience/WRFmet#29]
- `wrf_load()`: loads a snapshot of a single forecast hour from a WRF model run. It returns a _RasterBrick_ with a _RasterLayer_ for each requested variable from that point in time.
- `wrf_loadTimeSeries()`: loads multiple forecast hours from a WRF model run. It returns a _RasterBrick_ with a separate _RasterLayer_ (single variable) for each requested hour.

Maybe we could combine the two functions into `wrf_load()` and have it return a list of _RasterBricks_. Each brick would represent a forecast hour, and each _RasterLayer_ in a brick would store a variable. Or, if we think it's better to keep them separate, `wrf_load()` should at least have a more descriptive name.

One downside of the list approach is that if a user asks for just one variable over multiple hours, then a list of single-layered _RasterBricks_ will be returned which is a bit space inefficient.

**Comment by jonathancallahan** [comment]
Downloading enough data to create a timeseries is not feasible so all timeseries functionality is on permanent hold.
